### ISSUE TITLE
Graphite web does not allow time selections that don't end now or in the future

### ISSUE THREAD

**Issue by mwmanley** [brutasse/graphite-cyanite#13]
Changing the start time to the epoch of Unix time seems to do the trick:

https://github.com/mwmanley/graphite-cyanite/pull/1

It's a bit of a hammer, but without it I can't select two arbitrary start and end times.  In the current code, the end time has to be now or in the future or graphite web will not return results.

**Comment by brutasse** [comment]
Thank you, I've added this in graphite-cyanite 0.4.6.
